AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This CloudFormation stack creates an AWS Glue Data Catalog database,
  schemaless tables,
  a manually defined Glue table for CSV data stored in S3, and a Glue crawler
  configured to update the table schema automatically. The stack includes
  all necessary resources with required properties to manage Glue metadata
  efficiently within the current AWS account.

# -----------------------------------------------------------------------------
# Parameters section: Defines all customizable input values for the stack.
# -----------------------------------------------------------------------------

Parameters:
  StockDatabaseName:
    Type: String
    Description: Name of the Glue database
    Default: stock_data_rotemg

  DailyReturnTableName:
    Type: String
    Description: Name of the Glue table
    Default: daily_return

  HighestStockTableName:
    Type: String
    Description: Name of the Glue table
    Default: highest_stock

  MostVolatileTableName:
    Type: String
    Description: Name of the Glue table
    Default: most_volatile

  Top30DaysTableName:
    Type: String
    Description: Name of the Glue table
    Default: top_30_days

  BaseBucket:
    Type: String
    Default: "data-engineer-assignment-rotemg"
    Description: Base S3 bucket for our tables and input data

  InputS3Prefix:
    Type: String
    Default: "input-data"
    Description: The S3 key prefix for the input CSV data.

  OutputS3Prefix:
    Type: String
    Default: "output-data"
    Description: The S3 key prefix for the output data.

  ScriptS3Prefix:
    Type: String
    Default: "glue-scripts"
    Description: The S3 key for the PySpark script.

  DailyReturnJobName:
    Type: String
    Default: "AverageDailyReturnJob"
    Description: Name of the AWS Glue job.

  HighestStockJobName:
    Type: String
    Default: "HighestStockJob"
    Description: Name of the AWS Glue job.

  MostVolatileJobName:
    Type: String
    Default: "MostVolatileJob"
    Description: Name of the AWS Glue job.

  Top30DaysJobName:
    Type: String
    Default: "Top30DaysJob"
    Description: Name of the AWS Glue job.

  GlueVersion:
    Type: String
    Default: "4.0"
    Description: The version of AWS Glue to use for the job.

  WorkerType:
    Type: String
    Default: "G.1X"
    Description: The type of worker to use for the job.

  NumberOfWorkers:
    Type: Number
    Default: 2
    Description: The number of workers to allocate for the job.

  DailyReturnCrawlerName:
    Type: String
    Description: Name of the Glue crawler to discover the table schema.
    Default: DailyReturnCrawlerRotemg

  HighestStockCrawlerName:
    Type: String
    Description: Name of the Glue crawler to discover the table schema.
    Default: HighestStockCrawlerRotemg

  MostVolatileCrawlerName:
    Type: String
    Description: Name of the Glue crawler to discover the table schema.
    Default: MostVolatileCrawlerRotemg

  Top30DaysCrawlerName:
    Type: String
    Description: Name of the Glue crawler to discover the table schema.
    Default: Top30DaysCrawlerRotemg

# -----------------------------------------------------------------------------
# Resources section: Defines the AWS resources to be created.
# -----------------------------------------------------------------------------
Resources:

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref StockDatabaseName
        
  # --- Glue Tables: Defines the schema for the output data ---
  DailyReturnTable:
    Type: AWS::Glue::Table
    DependsOn: GlueDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref StockDatabaseName
      TableInput:
        Name: !Ref DailyReturnTableName
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          EXTERNAL: "TRUE"
        StorageDescriptor:
          Location: !Sub "s3://${BaseBucket}/${OutputS3Prefix}/${DailyReturnTableName}/"
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          Compressed: false
          StoredAsSubDirectories: false
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
            Parameters: {}          
          Columns:
          - Name: date
            Type: date
            Comment: "Date of the record"
          - Name: average_return
            Type: double
            Comment: "Average daily return"

  HighestStockTable:
    Type: AWS::Glue::Table
    DependsOn: GlueDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref StockDatabaseName
      TableInput:
        Name: !Ref HighestStockTableName
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          EXTERNAL: "TRUE"
        StorageDescriptor:
          Location: !Sub "s3://${BaseBucket}/${OutputS3Prefix}/${HighestStockTableName}/"
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          Compressed: false
          StoredAsSubDirectories: false
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
            Parameters: {}          
          Columns:
          - Name: ticker
            Type: string
            Comment: "stock ticker"
          - Name: avg_traded_worth
            Type: double
            Comment: "Average Traded worth"

  MostVolatileTable:
    Type: AWS::Glue::Table
    DependsOn: GlueDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref StockDatabaseName
      TableInput:
        Name: !Ref MostVolatileTableName
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          EXTERNAL: "TRUE"
        StorageDescriptor:
          Location: !Sub "s3://${BaseBucket}/${OutputS3Prefix}/${MostVolatileTableName}/"
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          Compressed: false
          StoredAsSubDirectories: false
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
            Parameters: {}          
          Columns:
          - Name: ticker
            Type: string
            Comment: "stock ticker"
          - Name: annualized_volatility
            Type: double
            Comment: "Annual volatility"

  Top30DaysTable:
    Type: AWS::Glue::Table
    DependsOn: GlueDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref StockDatabaseName
      TableInput:
        Name: !Ref Top30DaysTableName
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          EXTERNAL: "TRUE"
        StorageDescriptor:
          Location: !Sub "s3://${BaseBucket}/${OutputS3Prefix}/${Top30DaysTableName}/"
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          Compressed: false
          StoredAsSubDirectories: false
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
            Parameters: {}          
          Columns:
          - Name: ticker
            Type: string
            Comment: "stock ticker"
          - Name: date
            Type: date
            Comment: "Date of the record"
          - Name: 30_day_return
            Type: double
            Comment: "The 30 day return diff"

  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "stock-data-rotemg-GlueJobRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "glue.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
      Policies:
        - PolicyName: "S3AccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:ListBucket"
                  - "s3:DeleteObject"
                Resource:
                  - !Sub "arn:aws:s3:::${BaseBucket}"
                  - !Sub "arn:aws:s3:::${BaseBucket}/*"

  # --- Glue Jobs: Defines the PySpark jobs to run ---
  DailyReturnGlueJob:
    Type: AWS::Glue::Job
    DependsOn:
    - GlueDatabase
    - GlueJobRole
    Properties:
      Name: !Ref DailyReturnJobName
      Role: !Ref GlueJobRole
      WorkerType: !Ref WorkerType
      NumberOfWorkers: !Ref NumberOfWorkers
      GlueVersion: !Ref GlueVersion
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://${BaseBucket}/${ScriptS3Prefix}/daily_return_job.py"
        PythonVersion: "3"
      DefaultArguments:
        "--input_path": !Sub "s3://${BaseBucket}/${InputS3Prefix}"
        "--output_path": !Sub "s3://${BaseBucket}/${OutputS3Prefix}/${DailyReturnTableName}/"
        "--TempDir": !Sub "s3://${BaseBucket}/temporary/"
      MaxRetries: 0
      Timeout: 30

  HighestStockGlueJob:
    Type: AWS::Glue::Job
    DependsOn:
    - GlueDatabase
    - GlueJobRole
    Properties:
      Name: !Ref HighestStockJobName
      Role: !Ref GlueJobRole
      WorkerType: !Ref WorkerType
      NumberOfWorkers: !Ref NumberOfWorkers
      GlueVersion: !Ref GlueVersion
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://${BaseBucket}/${ScriptS3Prefix}/highest_stock_job.py"
        PythonVersion: "3"
      DefaultArguments:
        "--input_path": !Sub "s3://${BaseBucket}/${InputS3Prefix}"
        "--output_path": !Sub "s3://${BaseBucket}/${OutputS3Prefix}/${HighestStockJobName}/"
        "--TempDir": !Sub "s3://${BaseBucket}/temporary/"
      MaxRetries: 0
      Timeout: 30

  MostVolatileGlueJob:
    Type: AWS::Glue::Job
    DependsOn:
    - GlueDatabase
    - GlueJobRole
    Properties:
      Name: !Ref MostVolatileJobName
      Role: !Ref GlueJobRole
      WorkerType: !Ref WorkerType
      NumberOfWorkers: !Ref NumberOfWorkers
      GlueVersion: !Ref GlueVersion
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://${BaseBucket}/${ScriptS3Prefix}/most_volatile_job.py"
        PythonVersion: "3"
      DefaultArguments:
        "--input_path": !Sub "s3://${BaseBucket}/${InputS3Prefix}"
        "--output_path": !Sub "s3://${BaseBucket}/${OutputS3Prefix}/${MostVolatileTableName}/"
        "--TempDir": !Sub "s3://${BaseBucket}/temporary/"
      MaxRetries: 0
      Timeout: 30

  Top30DaysGlueJob:
    Type: AWS::Glue::Job
    DependsOn:
    - GlueDatabase
    - GlueJobRole
    Properties:
      Name: !Ref Top30DaysJobName
      Role: !Ref GlueJobRole
      WorkerType: !Ref WorkerType
      NumberOfWorkers: !Ref NumberOfWorkers
      GlueVersion: !Ref GlueVersion
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://${BaseBucket}/${ScriptS3Prefix}/top_30_days_job.py"
        PythonVersion: "3"
      DefaultArguments:
        "--input_path": !Sub "s3://${BaseBucket}/${InputS3Prefix}"
        "--output_path": !Sub "s3://${BaseBucket}/${OutputS3Prefix}/${Top30DaysTableName}/"
        "--TempDir": !Sub "s3://${BaseBucket}/temporary/"
      MaxRetries: 0
      Timeout: 30

  # --- Glue Crawlers: Defines the crawlers to automatically update partitions ---

  DailyReturnCrawler:
    Type: AWS::Glue::Crawler
    DependsOn:
      - DailyReturnTable
      - GlueJobRole
    Properties:
      Name: !Ref DailyReturnCrawlerName
      Role: !GetAtt GlueJobRole.Arn
      DatabaseName: !Ref StockDatabaseName
      Targets:
        S3Targets:
          - Path: !Sub "s3://${BaseBucket}/${OutputS3Prefix}/${DailyReturnTableName}/"
      TablePrefix: ""
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_EVERYTHING

  HighestStockCrawler:
    Type: AWS::Glue::Crawler
    DependsOn:
      - HighestStockTable
      - GlueJobRole
    Properties:
      Name: !Ref HighestStockCrawlerName
      Role: !GetAtt GlueJobRole.Arn
      DatabaseName: !Ref StockDatabaseName
      Targets:
        S3Targets:
          - Path: !Sub "s3://${BaseBucket}/${OutputS3Prefix}/${HighestStockTableName}/"
      TablePrefix: ""
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_EVERYTHING

  MostVolatileCrawler:
    Type: AWS::Glue::Crawler
    DependsOn:
      - MostVolatileTable
      - GlueJobRole
    Properties:
      Name: !Ref MostVolatileCrawlerName
      Role: !GetAtt GlueJobRole.Arn
      DatabaseName: !Ref StockDatabaseName
      Targets:
        S3Targets:
          - Path: !Sub "s3://${BaseBucket}/${OutputS3Prefix}/${MostVolatileTableName}/"
      TablePrefix: ""
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_EVERYTHING

  Top30DaysCrawler:
    Type: AWS::Glue::Crawler
    DependsOn:
      - Top30DaysTable
      - GlueJobRole
    Properties:
      Name: !Ref Top30DaysCrawlerName
      Role: !GetAtt GlueJobRole.Arn
      DatabaseName: !Ref StockDatabaseName
      Targets:
        S3Targets:
          - Path: !Sub "s3://${BaseBucket}/${OutputS3Prefix}/${Top30DaysTableName}/"
      TablePrefix: ""
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_EVERYTHING

# -----------------------------------------------------------------------------
# Outputs section: Defines values exported from the stack.
# -----------------------------------------------------------------------------
Outputs:
  StockDatabaseName:
    Description: Name of the Glue database
    Value: !Ref StockDatabaseName
    Export:
      Name: StockDatabaseName

  DailyReturnTableName:
    Description: Name of the Glue table
    Value: !Ref DailyReturnTableName
    Export:
      Name: DailyReturnTableName

  HighestStockTableName:
    Description: Name of the Glue table
    Value: !Ref HighestStockTableName
    Export:
      Name: HighestStockTableName

  MostVolatileTableName:
    Description: Name of the Glue table
    Value: !Ref MostVolatileTableName
    Export:
      Name: MostVolatileTableName

  Top30DaysTableName:
    Description: Name of the Glue table
    Value: !Ref Top30DaysTableName
    Export:
      Name: Top30DaysTableName

  GlueJobRoleArn:
    Description: The ARN of the Glue job IAM role
    Value: !GetAtt GlueJobRole.Arn

  DailyReturnGlueJob:
    Description: The name of the AWS Glue job created by this stack.
    Value: !Ref DailyReturnGlueJob
 
  HighestStockGlueJob:
    Description: The name of the AWS Glue job created by this stack.
    Value: !Ref HighestStockGlueJob

  MostVolatileGlueJob:
    Description: The name of the AWS Glue job created by this stack.
    Value: !Ref MostVolatileGlueJob

  Top30DaysGlueJob:
    Description: The name of the AWS Glue job created by this stack.
    Value: !Ref Top30DaysGlueJob