AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This CloudFormation stack creates an AWS Glue Data Catalog database,
  schemaless tables,
  a manually defined Glue table for CSV data stored in S3, and a Glue crawler
  configured to update the table schema automatically. The stack includes
  all necessary resources with required properties to manage Glue metadata
  efficiently within the current AWS account.

Parameters:
  StockDatabaseName:
    Type: String
    Description: Name of the Glue database
    Default: stock_data_rotemg

  DailyReturnTableName:
    Type: String
    Description: Name of the Glue table
    Default: daily_return

  BaseBucket:
    Type: String
    Default: "data-engineer-assignment-rotemg"
    Description: Base S3 bucket for our tables and input data

  InputS3Prefix:
    Type: String
    Default: "input-data"
    Description: The S3 key prefix for the input CSV data.

  OutputS3Prefix:
    Type: String
    Default: "output-data"
    Description: The S3 key prefix for the output data.

  ScriptS3Prefix:
    Type: String
    Default: "glue-scripts"
    Description: The S3 key for the PySpark script.

  JobName:
    Type: String
    Default: "AverageDailyReturnJob"
    Description: Name of the AWS Glue job.

  GlueVersion:
    Type: String
    Default: "4.0"
    Description: The version of AWS Glue to use for the job.

  WorkerType:
    Type: String
    Default: "G.1X"
    Description: The type of worker to use for the job.

  NumberOfWorkers:
    Type: Number
    Default: 2
    Description: The number of workers to allocate for the job.

  DailyReturnCrawlerName:
    Type: String
    Description: Name of the Glue crawler to discover the table schema.
    Default: DailyReturnCrawler

Resources:

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref StockDatabaseName

  GlueTable:
    Type: AWS::Glue::Table
    DependsOn: GlueDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref StockDatabaseName
      TableInput:
        Name: !Ref DailyReturnTableName
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          EXTERNAL: "TRUE"
        StorageDescriptor:
          Location: !Sub "s3://${BaseBucket}/${OutputS3Prefix}/${DailyReturnTableName}/"
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          Compressed: false
          StoredAsSubDirectories: false
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
            Parameters: {}
        # Removed explicit column definitions as the crawler will handle schema discovery.


  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "stock-data-rotemg-GlueJobRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "glue.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
      Policies:
        - PolicyName: "S3AccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:ListBucket"
                  - "s3:DeleteObject"
                Resource:
                  - !Sub "arn:aws:s3:::${BaseBucket}"
                  - !Sub "arn:aws:s3:::${BaseBucket}/*"

  DailyReturnGlueJob:
    Type: AWS::Glue::Job
    DependsOn:
    - GlueDatabase
    - GlueJobRole
    Properties:
      Name: !Ref JobName
      Role: !Ref GlueJobRole
      WorkerType: !Ref WorkerType
      NumberOfWorkers: !Ref NumberOfWorkers
      GlueVersion: !Ref GlueVersion
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://${BaseBucket}/${ScriptS3Prefix}/daily_return_job.py"
        PythonVersion: "3"
      DefaultArguments:
        "--input_path": !Sub "s3://${BaseBucket}/${InputS3Prefix}"
        "--output_path": !Sub "s3://${BaseBucket}/${OutputS3Prefix}"
        "--TempDir": !Sub "s3://${BaseBucket}/temporary/"
      MaxRetries: 0
      Timeout: 30

Outputs:
  StockDatabaseName:
    Description: Name of the Glue database
    Value: !Ref StockDatabaseName
    Export:
      Name: StockDatabaseName

  DailyReturnTableName:
    Description: Name of the Glue table
    Value: !Ref DailyReturnTableName
    Export:
      Name: DailyReturnTableName

  GlueJobRoleArn:
    Description: The ARN of the Glue job IAM role
    Value: !GetAtt GlueJobRole.Arn

  DailyReturnGlueJob:
    Description: The name of the AWS Glue job created by this stack.
    Value: !Ref DailyReturnGlueJob
 